#define TXT_NO 						"No"
#define TXT_OFF 					"Off"
#define TXT_STYLES					"Styles"
#define TXT_STYLE					"Style"
#define TXT_YES 					"Yes"
#define TXT_SKIN_EDITOR 				"Skin Editor"
#define TXT_VISUALISATIONS 				"Visualisations"
#define TXT_EDIT_THE_APPEARANCE_OF_WALKMAN_LAYOUT 	"Edit the appearance of WALKMAN layout"
#define TXT_ENABLED 					"Enabled"
#define TXT_POSITION 					"Position"
#define TXT_BACKGROUND_COLOR 				"Background Color"
#define TXT_ELAPSED_BAR_COLOR 				"Elapsed Bar Color"
#define TXT_ALIGN 					"Align"
#define TXT_LEFT 					"Left"
#define TXT_RIGHT 					"Right"
#define TXT_CENTER 					"Center"
#define TXT_FONT_SIZE 					"Font Size"
#define TXT_TEXT_COLOR 					"Text Color"
#define TXT_TITLE 					"Title"
#define TXT_ARTIST 					"Artist"
#define TXT_ALBUM 					"Album"
#define TXT_GENRE 					"Genre"
#define TXT_TOTAL_TIME 					"Total Time"
#define TXT_ELAPSED_TIME 				"Elapsed Time"
#define TXT_REMAINING_TIME 				"Remaining Time"
#define TXT_EXTENSION 					"Extension"
#define TXT_BITRATE 					"Bitrate"
#define TXT_TOTAL_TRACK_NUMBER 				"Total Track Number"
#define TXT_CURRENT_TRACK_NUMBER 			"Current Track Number"
#define TXT_SHUFFLE_ICON 				"Shuffle Icon"
#define TXT_LOOP_ICON 					"Loop Icon"
#define TXT_EQ_ICON 					"EQ Icon"
#define TXT_PLAYER_STATE_ICON 				"Player State Icon"
#define TXT_TITLE_ICON 					"Title Icon"
#define TXT_ARTIST_ICON 				"Artist Icon"
#define TXT_ALBUM_ICON 					"Album Icon"
#define TXT_WHEEL_BG_ICON 				"Wheel BG Icon"
#define TXT_WHEEL_UP_ICON 				"Wheel Up Icon"
#define TXT_WHEEL_DOWN_ICON 				"Wheel Down Icon"
#define TXT_WHEEL_LEFT_ICON 				"Wheel Left Icon"
#define TXT_WHEEL_RIGHT_ICON 				"Wheel Right Icon"
#define TXT_WHEEL_CENTER_ICON 				"Wheel Center Icon"
#define TXT_BACKGROUND_IMAGE 				"Background Image"
#define TXT_OVERLAY_IMAGE 				"Overlay Image"
#define TXT_PROGRESS_BAR 				"Progress Bar"
#define TXT_VOLUME_BAR 					"Volume Bar"
#define TXT_DISABLED 					"Disabled"
#define TXT_ALBUM_ART 					"Album Art"
#define TXT_FULLSCREEN 					"Fullscreen"
#define TXT_SHOW_SOFTKEY 				"Show Softkey"
#define TXT_SAVE 					"Save"
#define TXT_PORTRAIT 					"Portrait"
#define TXT_LANDSCAPE 					"Landscape"
#define TXT_WALKMAN_GUI 				"Walkman GUI"
#define TXT_SKINS 					"Skins"
#define TXT_CHANGES_MADE 				"Changes made"
#define TXT_SAVE2 					"Save?"
#define TXT_SKIN_UPDATED 				"Skin updated"
#define TXT_SKIN_NOT_UPDATED                            "Skin not updated"
#define TXT_SET_THIS_SKIN 				"Set this skin"
#define TXT_EDIT_SKIN 					"Edit skin"
#define TXT_AUTHORS_NAME 				"Author's Name:"
#define TXT_SKIN_HASNT_BEEN_CONFIGURED_YET 		"Skin hasn't been configured yet!"
#define TXT_CONFIGURE_NOW 				"Configure now?"
