#define TXT_NO 										"Nie"
#define TXT_OFF 									"Wy³¹cz"
#define TXT_STYLES									"Style"
#define TXT_STYLE									"Styl"
#define TXT_YES 									"Tak"
#define TXT_SKIN_EDITOR 							"Skórki"
#define TXT_VISUALISATIONS 							"Wizualizacje"
#define TXT_EDIT_THE_APPEARANCE_OF_WALKMAN_LAYOUT 	"Edytuj wygl¹d uk³adu WALKMAN"
#define TXT_ENABLED 								"W³¹czony"
#define TXT_POSITION 								"Pozycja"
#define TXT_BACKGROUND_COLOR 						"Kolor t³a"
#define TXT_ELAPSED_BAR_COLOR 						"Kolor paska czasu up³yniêtego"
#define TXT_ALIGN 									"Wyrównanie"
#define TXT_LEFT 									"Lewo"
#define TXT_RIGHT 									"Prawo"
#define TXT_CENTER 									"Œrodek"
#define TXT_FONT_SIZE 								"Rozmiar czcionki"
#define TXT_TEXT_COLOR 								"Kolor czcionki"
#define TXT_TITLE 									"Tytu³"
#define TXT_ARTIST 									"Artysta"
#define TXT_ALBUM 									"Album"
#define TXT_GENRE 									"Gatunek"
#define TXT_TOTAL_TIME 								"Czas ca³kowity"
#define TXT_ELAPSED_TIME 							"Czas up³yniêty"
#define TXT_REMAINING_TIME 							"Czas pozosta³y"
#define TXT_EXTENSION 								"Rozszerzenie"
#define TXT_BITRATE 								"Bitrate"
#define TXT_TOTAL_TRACK_NUMBER 						"Ca³kowita liczba utw."
#define TXT_CURRENT_TRACK_NUMBER 					"Nr. bie¿¹cego utworu"
#define TXT_SHUFFLE_ICON 							"Ikona odt. losowego"
#define TXT_LOOP_ICON 								"Ikona pêtli"
#define TXT_EQ_ICON 								"Ikona korektora"
#define TXT_PLAYER_STATE_ICON 						"Ikona stanu odt."
#define TXT_TITLE_ICON 								"Ikona tytu³u"
#define TXT_ARTIST_ICON 							"Ikona artysty"
#define TXT_ALBUM_ICON 								"Ikona albumu"
#define TXT_WHEEL_BG_ICON 							"Ikona t³a ko³a"
#define TXT_WHEEL_UP_ICON 							"Ikona ko³a - góra"
#define TXT_WHEEL_DOWN_ICON 						"Ikona ko³a - dó³"
#define TXT_WHEEL_LEFT_ICON 						"Ikona ko³a - lewo"
#define TXT_WHEEL_RIGHT_ICON 						"Ikona ko³a - prawo"
#define TXT_WHEEL_CENTER_ICON 						"Ikona ko³a - œrodek"
#define TXT_BACKGROUND_IMAGE 						"Obraz t³a"
#define TXT_OVERLAY_IMAGE 							"Obraz nak³adki"
#define TXT_PROGRESS_BAR 							"Pasek postêpu"
#define TXT_VOLUME_BAR 								"Pasek g³oœnoœci"
#define TXT_DISABLED 								"Wy³¹czone"
#define TXT_ALBUM_ART 								"Ok³adka albumu"
#define TXT_FULLSCREEN 								"Pe³ny ekran"
#define TXT_SHOW_SOFTKEY 							"Poka¿ przyciski"
#define TXT_SAVE 									"Zapisz"
#define TXT_PORTRAIT 								"Pionowy"
#define TXT_LANDSCAPE 								"Poziomy"
#define TXT_WALKMAN_GUI 							"Ustawienia GUI"
#define TXT_SKINS 									"Skórki"
#define TXT_CHANGES_MADE 							"Dokonano zmian"
#define TXT_SAVE2 									"Zapisaæ?"
#define TXT_SKIN_UPDATED 							"Skórka zaktualizowana"
#define TXT_SKIN_NOT_UPDATED                                                    "Skórka niezaktualizowana"
#define TXT_SET_THIS_SKIN                                                       "Ustaw t¹ skórkê"
#define TXT_SET_THIS_SKIN_2ND                                                   "Instalacja skórki"
#define TXT_EDIT_SKIN                                                           "Edytuj skórkê"
#define TXT_EDIT_SKIN_2ND                                                       "Zmiana parametrów"
#define TXT_AUTHORS_NAME                                                        "Nick autora:"
#define TXT_SKIN_HASNT_BEEN_CONFIGURED_YET                      "Skórka nie zosta³a jeszcze skonfigurowana!"
#define TXT_CONFIGURE_NOW                                                       "Skonfigurowaæ teraz?"
