#ifndef __UITEXTRENDERING_TYPES_H__
#define __UITEXTRENDERING_TYPES_H__

/**
 * @addtogroup TextRendering
 * @{
 */

typedef enum 
{
  TEXTRENDERING_UED_UNSPECIFIED, 
  TEXTRENDERING_UED_NO_CHARACTERS_LEFT_TO_COMPOSE,
  TEXTRENDERING_UED_POINT_NOT_IN_LAYOUT,
  TEXTRENDERING_UED_FONT_STYLE_NOT_SET,
  TEXTRENDERING_UED_LINE_EXCEEDED_ASCENDER_LIMIT,
  TEXTRENDERING_UED_LINE_EXCEEDED_DESCENDER_LIMIT,
  TEXTRENDERING_UED_INVALID_INLINE_OBJECT_INDEX,
  TEXTRENDERING_UED_COULD_NOT_FIT_WIDTH,
  TEXTRENDERING_UED_INIT_FONT_ENGINE_FAILED,
  TEXTRENDERING_UED_DONE_FONT_ENGINE_FAILED,
  TEXTRENDERING_UED_INIT_FONT_FAILED,
  TEXTRENDERING_UED_DONE_FONT_FAILED,
  TEXTRENDERING_UED_INIT_STYLE_FAILED,
  TEXTRENDERING_UED_DONE_STYLE_FAILED,
  TEXTRENDERING_UED_GET_TABLE_FAILED,
  TEXTRENDERING_UED_RELEASE_TABLE_FAILED,
  TEXTRENDERING_UED_MAPCHAR_FAILED,
  TEXTRENDERING_UED_INIT_GLYPH_FAILED,
  TEXTRENDERING_UED_DONE_GLYPH_FAILED,
  TEXTRENDERING_UED_GET_GLYPH_PTS_FAILED,
  TEXTRENDERING_UED_INVALID_CHARID,
  TEXTRENDERING_UED_INVALID_FONTID,
  TEXTRENDERING_UED_CMAP_PROBLEM,
  TEXTRENDERING_UED_ARGUMENT_OUT_OF_RANGE,
  TEXTRENDERING_UED_INVALID_BYTE_ORDER_MARK,
  TEXTRENDERING_UED_INVALID_RESOURCE_VERSION,
  TEXTRENDERING_UED_INVALID_RESOURCE_TAG,
  TEXTRENDERING_UED_INVALID_CONTAINER_ID,
  TEXTRENDERING_UED_NO_CONTAINERS_SPECIFIED,
  TEXTRENDERING_UED_INVALID_LAYOUT_MODE,
  TEXTRENDERING_UED_INVALID_SHAPE_ID,
  TEXTRENDERING_UED_UNSUPPORTED_GLYPHS_FLOW,
  TEXTRENDERING_UED_UNSUPPORTED_LINE_FLOW,
  TEXTRENDERING_UED_INVALID_CARET,
  TEXTRENDERING_UED_LINE_SPACING_ATTRIBUTES_CHANGED,
  TEXTRENDERING_UED_INVALID_INLINE_IMAGE_HANDLE,
  TEXTRENDERING_UED_INVALID_MODE

} TUITextRenderingUed;
/**@}*/

#endif
