#ifndef _SCREENSHOT_H_
#define _SCREENSHOT_H_

#include "..\\include\classes\classes.h"

typedef enum
{
  AUDIO_NOTIFICATION_RINGER,
  AUDIO_NOTIFICATION_ALARM,
  AUDIO_NOTIFICATION_REQUEST,
  AUDIO_NOTIFICATION_REQUEST_CALL,
  AUDIO_NOTIFICATION_SUCCESS,
  AUDIO_NOTIFICATION_FAILURE,
  AUDIO_NOTIFICATION_PROGRESS,
  AUDIO_NOTIFICATION_NOTIFICATION,
  AUDIO_NOTIFICATION_REMINDER,
  AUDIO_NOTIFICATION_DISCONNECTED,
  AUDIO_NOTIFICATION_DISCREET,
  AUDIO_NOTIFICATION_LOWBATTERY,
  AUDIO_NOTIFICATION_EMPTYBATTERY,
  AUDIO_NOTIFICATION_CHARGING,
  AUDIO_NOTIFICATION_VIDEO,
  AUDIO_NOTIFICATION_RETRYSUCCESS,
  AUDIO_NOTIFICATION_TIMER,
  AUDIO_NOTIFICATION_MESSAGEALERT_SILENT,
  AUDIO_NOTIFICATION_MESSAGECLICK,
  AUDIO_NOTIFICATION_MESSAGEALERT1,
  AUDIO_NOTIFICATION_MESSAGEALERT2,
  AUDIO_NOTIFICATION_MESSAGEALERT3,
  AUDIO_NOTIFICATION_MESSAGEALERT4,
  AUDIO_NOTIFICATION_MESSAGEALERT5,
  AUDIO_NOTIFICATION_MESSAGEALERT6,
  AUDIO_NOTIFICATION_CAMERASHUTTER,
  AUDIO_NOTIFICATION_CAMERATIMER,
  AUDIO_NOTIFICATION_CAMERA_FOCUS_SUCCESS,
  AUDIO_NOTIFICATION_CAMERA_BURST,

  AUDIO_NOTIFICATION_LAST
} TAudio_Notification;

#define MAX_FILENAME_LEN 50

#define SNAPSHOT_PATH L"/tpa/user/image/SnapShots"

void Screenshoter(int width, int height);

#endif
