#ifndef _LNG_H_
#define _LNG_H_

#define TIME_CFG_NAME "Standby Clock"
#define TIME2_CFG_NAME "Status Clock"
#define DATE_CFG_NAME "Date"
#define WEEKDAY_CFG_NAME "Weekday"
#define ALARM_CFG_NAME "Alarm clock"
#define PROFILE_CFG_NAME "Profile name"
#define HEAP_CFG_NAME "Heap info"
#define TIMER_CFG_NAME "Timer"
#define CALL_CFG_NAME "Call time"
#define SIGNAL_CFG_NAME "Signal strenght"
#define NETWORK_CFG_NAME "Network name"
#define BATT_CFG_NAME "Battery remaining"
#define CHARGE_CFG_NAME "Charging current"
#define BATTTEMP_CFG_NAME "Battery temp"
#define SYSTEMP_CFG_NAME "System temp"
#define PHONE_CFG_NAME "Phone memory"
#define CARD_CFG_NAME "Memory card"
#define MUSIC_CFG_NAME "Music Widget"
#define RADIO_CFG_NAME "FM Radio"
#define NET_ICN_CFG_NAME "Signal icon"
#define BATT_ICN_CFG_NAME "Battery icon"
#define STATUS_CFG_NAME "Statusrow"
#define STATUSBG_CFG_NAME "Statusrow BG"

#define SHOW_MSG "Show"
#define MODE_MSG "Format"
#define FONT_MSG "Text size"
#define ALIGN_MSG "Text position"
#define HIGHLIGHT_MSG "Text highlight"
#define TCOLOR_MSG "Text color"
#define HCOLOR_MSG "Highlight Color"
#define UCOLOR_MSG "Underline Color"
#define VISUAL_MSG "Edit Visual"

#define HIGHLIGHT_NO_MSG "No"
#define HIGHLIGHT_FULLV1_MSG "Full v1"
#define HIGHLIGHT_FULLV2_MSG "Full v2"
#define HIGHLIGHT_SHADOW_MSG "Shadow"

#define LEFT_MSG "Left"
#define RIGHT_MSG "Right"
#define CENTER_MSG "Center"

#define FIRST_MSG "Show first?"
#define REDUCED_MSG "Short"
#define FULL_MSG "Full"
#define SEC_MSG "Second"
#define DBM_MSG "Show dBm"
#define FILL_BY_ROW_MSG "Fill on page."
#define ROW_MAX_MSG "Max. lines"
#define COL_MAX_MSG "Max. columns"
#define CHARGINGONLY_MSG "Current charge"
#define MASSAGE_MSG "Text"
#define TYPE_MSG "Memory info"
#define FREE_MSG "Free"
#define USED_MSG "Used"
#define FORMAT_MSG "Format"
#define PERCENT_MSG "Percent"
#define KB_MSG "Kb"
#define MB_MSG "Mb"
#define GB_MSG "Gb"
#define FILL_MSG "Fill in"
#define RL_MSG "left to right"
#define LR_MSG "right to left"

#define TITLE_MSG "Title"
#define ARTIST_MSG "Artist"
#define FREQ_MSG "Frequency"
#define NAME_MSG "Name"

#define TITLE_ONLY_MSG "Title"
#define ARTIST_ONLY_MSG "Artist"
#define TITLE_AND_ARTIST_MSG "Title & Artist"

#define FREQ_ONLY_MSG "Freq. only"
#define NAME_ONLY_MSG "Name only"
#define FREQ_AND_NAME_MSG "Freq and Name"

#define HELP_STRING "Keys:\n'*' to select & edit item\n'#' - to exit without saving\n'5' - to save and exit\n'Up & Down' - change font size\n'1' - set underline\n'3' - change font style\n'2 & 4' - move Y pos\n'4 & 6' - move X Pos\n'7' - change alignment\n'0' - change highlight."
#endif
